/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "common.h"
#include "fang_key_MakeKey.h"



JNIEXPORT jint JNICALL Java_fang_key_MakeKey_makeKeyFile(JNIEnv * env, jobject thiz,  jstring str)
{
	const char *s =  (*env)->GetStringUTFChars(env, str, 0); //»ñÈ¡×Ö·û´®

	int ret =  master(s);
	if(ret != 0){
		return -1;
	}

	return 0;
}
