/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>

#include "com_example_myjni_MyJni.h"

//-------------------------------------------------------
// * fang 说明：
 //* jni.c文件中 传入参数 与 返回参数 若为数组（指针）则需函数转换
 //* 如果为普通的变量eg: int(jint) float(jfloat) char(jbyte) bool(jboolean)
 //*        则可以自由转化  等效。eg:返回jint 可以 return 0，或 return (int)a 或return (jint)a;
 //*                        eg：传入jint 可以 int a = 传入参入。
 //*        但 传入/返回  字符串、数组、等指针类，需要函数转换
//-------------------------------------------------------


JNIEXPORT void JNICALL Java_com_example_myjni_MyJni_MyJniTestA(JNIEnv *env, jobject thiz)
{
//	LOGI("into _MyJniTestA");
	int i = 88;
    int a = 10;
    a++;
//    LOGI("into _MyJniTestA end !");
}


JNIEXPORT jint JNICALL Java_com_example_myjni_MyJni_MyJniTestB(JNIEnv *env, jobject thiz, jstring str)
{

	const char *s = (*env)->GetStringUTFChars(env, str, 0);
    int a5 = 5,a6 = 6, a7 = 7;
    jint a8 = 8;
    jint a9 = 9;
    if(strstr(s,"V1") ){
    	return 1;
    }else if(strstr(s,"V2") ){
    	return 1;
    }else if(s[0] == 'X' ){  //测试 OK
    	return 99;
    }else if(strstr(s,"V3") ){
    	return (jint)3;
    }else if(strstr(s,"V4") ){
    	return (jint)4;
    }else if(s[0] == 'Y' ){  //测试 OK
    	return (jint)88;
    }else if(strstr(s,"V5") ){
    	return a5;
    }else if(strstr(s,"V6") ){
    	return a6;
    }else if(strstr(s,"V7") ){
    	return a8;
    }else if(strstr(s,"V8") ){
    	return a6;
    }else if(strstr(s,"V9") ){
    	return a9;
    }else if(strstr(s,"VB") ){  //未有见效生成文件
    	system("echo fang > /mnt/sdcard/fangnew.txt");
    	system("echo `fang` > /mnt/sdcard/fangnew1.txt");
    	system("echo 'fang' > /mnt/sdcard/fangnew2.txt");
    }
    return 0;

}

JNIEXPORT jstring JNICALL Java_com_example_myjni_MyJni_MyJniTestC(JNIEnv *env, jobject thiz, jstring str)
{
//	LOGI("into _MyJniTestC",  str);
	const char *s = (*env)->GetStringUTFChars(env, str, 0);
	 char fs[100] = "xxxxxoooo";
	 if(strstr(s,"strcpy")){
		 strcpy(fs, s);
	 }else if(strstr(s,"strcat")){
		 strcat(s, fs);  //不允许对传入参数操作，会报错的！！！
	 }
	 (*env)->ReleaseStringUTFChars(env, str, s);
	 return (*env)->NewStringUTF(env, fs);
}

JNIEXPORT jint JNICALL Java_com_example_myjni_MyJni_MyJniFunA(JNIEnv *env, jobject thiz, jint a, jfloat b, jbyte c)
{
    int a1 = a;
    float b1 = b;
    char c1 = c;
   if(a1 == 1 && b1 == (float)0.88 && c1 == 99)
   {
	   return 1;
   }else if( a1 == 2)
   {
	   return (jint)2;
   }

   return 0;
}

JNIEXPORT jstring JNICALL Java_com_example_myjni_MyJni_MyJniFunB(JNIEnv *env, jobject thiz, jstring str1, jstring str2)
{
   char s[200];
   strcpy(s, str1);
   strcat(s, str2);

   return (*env)->NewStringUTF(env, s);
}

JNIEXPORT jint JNICALL Java_com_example_myjni_MyJni_MyJniFunC(JNIEnv *env, jobject thiz, jint a, jint b, jint c)
{
	int a1 = a;
	int b1 = b;
	int c1 = c;
	int d = a1+b1+c1;
	return d;
}

JNIEXPORT jstring JNICALL Java_com_example_myjni_MyJni_MyJniFunAA(JNIEnv *env, jobject thiz, jintArray as)
{
	int lenth = (*env)->GetArrayLength(env, as);//获取数组长度
	int *arrp =  (*env)->GetIntArrayElements(env, as, 0); //获取数组指针

	 return (*env)->NewStringUTF(env, "into MyJni> MyJniFunAA !");
}

JNIEXPORT jintArray JNICALL Java_com_example_myjni_MyJni_MyJniFunAB(JNIEnv *env, jobject thiz, jintArray as)
{
	int lenth = (*env)->GetArrayLength(env, as);//获取数组长度
	int *arrp =  (*env)->GetIntArrayElements(env, as, 0); //获取数组指针
	return arrp;
}
JNIEXPORT jobjectArray JNICALL Java_com_example_myjni_MyJni_MyJniFunAC(JNIEnv *env, jobject thiz, jobjectArray sstr)
{
	int lenth = (*env)->GetArrayLength(env, sstr);//获取数组长度
	const char *s = (*env)->GetStringUTFChars(env, sstr, 0);
	return s;
}

