/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fang_key_MakeKey */

#ifndef _Included_fang_key_MakeKey
#define _Included_fang_key_MakeKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fang_key_MakeKey
 * Method:    makeKeyFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fang_key_MakeKey_makeKeyFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fang_key_MakeKey
 * Method:    getCpuSerial
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fang_key_MakeKey_getCpuSerial
  (JNIEnv *, jobject);

/*
 * Class:     fang_key_MakeKey
 * Method:    getAPPKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fang_key_MakeKey_getAPPKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
