/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "common.h"
#include "fang_key_MakeKey.h"



JNIEXPORT jint JNICALL Java_fang_key_MakeKey_makeKeyFile(JNIEnv * env, jobject thiz,  jstring str)
{
	const char *s =  (*env)->GetStringUTFChars(env, str, 0); //获取字符串

	int ret =  master(s);
	if(ret != 0){
		return -1;
	}

	return 0;
}

JNIEXPORT jstring JNICALL Java_fang_key_MakeKey_getCpuSerial(JNIEnv * env, jobject thiz)
{
	char cpuInfoSerial[500];
	if( getCpuInfoSerial(cpuInfoSerial) != 0)
	{
		 return (*env)->NewStringUTF(env, "");
	}
	 return (*env)->NewStringUTF(env, cpuInfoSerial);
}

JNIEXPORT jstring JNICALL Java_fang_key_MakeKey_getAPPKey(JNIEnv * env, jobject thiz)
{
//	const char *s =  (*env)->GetStringUTFChars(env, str, 0); //获取字符串

	char cpuInfoSerial[500];
	if( getCpuInfoSerial(cpuInfoSerial) != 0)
	{
		 return (*env)->NewStringUTF(env, "");
	}
	char effectKey[500];
	if( keyEncrpyt(cpuInfoSerial, effectKey) < 6 )
	{
		return (*env)->NewStringUTF(env, "");
	}

	 return (*env)->NewStringUTF(env, effectKey);
}


